language: python
python:
  - "2.6"
  - "2.7"
matrix:
  allow_failures:
    - python: "2.6"
install: "pip install -r requirements_for_tests.txt --use-mirrors"
script: ./run_tests.sh
branches:
  except:
    - release
